# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='site_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
